### ISSUE TITLE
Reclassify UberCloud under HPC Management Tools

### ISSUE THREAD

**Issue by tj2040** [kjrstory/awesome-cloud-hpc#13]
Hello kjrstory. I work for UberCloud and we're a Cloud HPC middleware, not a SAAS. Also, we've rebranded as SIMR (Sim-er). :)

**Comment by kjrstory** [comment]
Hello, @tj2040 
I am already aware of your company's rebranding. #11 
However, I am unable to understand what kind of software SimR is.
This is because there are no screenshots or demos on the website.
So, I will remove UberCloud from the SaaS section for now, close this issue, and leave only the original issue(#11)open until we determine which category SimR should be placed in.

**Comment by tj2040** [comment]
Thanks for responding.

I took the lack of screenshots on our website to our marketing head today.
In the meanwhile, here's our YouTube page that has demo videos.
***@***.***

It's similar to Flight Environment
<https://www.openflighthpc.org/latest/docs/flight-environment/> in that it
provides a web GUI for running jobs on cloud HPC. In addition to that, we
run and maintain the HPC application stack for the enterprise. I hope that
helps.

Thanks!
